#!/usr/bin/env bash
# =============================================================================
# Homelab Server Security Hardening Script
# Target: Ubuntu 24.04.4 LTS (homelab)
# Run as: dev user with sudo privileges
# Usage:  chmod +x harden-homelab.sh && sudo ./harden-homelab.sh
# =============================================================================
set -euo pipefail

# --- Configuration -----------------------------------------------------------
LAN_IP="192.168.8.101"
TAILSCALE_IP="100.114.75.127"
LAN_CIDR="192.168.0.0/16"
LAN_CIDR_NARROW="192.168.8.0/24"
TAILSCALE_CIDR="100.64.0.0/10"
ALLOWED_SSH_USERS="dev svc-ai-agent"
LOG_FILE="/var/log/hardening-$(date +%Y%m%d-%H%M%S).log"

# --- Helpers -----------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[+]${NC} $*" | tee -a "$LOG_FILE"; }
warn() { echo -e "${YELLOW}[!]${NC} $*" | tee -a "$LOG_FILE"; }
err()  { echo -e "${RED}[x]${NC} $*" | tee -a "$LOG_FILE"; }

confirm() {
    local msg="$1"
    echo -e "${YELLOW}[?]${NC} $msg"
    read -rp "    Continue? [y/N]: " answer
    [[ "$answer" =~ ^[Yy]$ ]] || { warn "Skipped by user."; return 1; }
}

# --- Preflight ---------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root (use sudo)."
    exit 1
fi

log "Hardening started at $(date). Logging to $LOG_FILE"
log "Server: $(hostname) | OS: $(lsb_release -ds) | Kernel: $(uname -r)"
echo ""

# =============================================================================
# STEP 1: Consolidate SSH Configuration
# =============================================================================
log "=== STEP 1: SSH Configuration ==="

# Back up existing configs
SSH_BACKUP="/etc/ssh/sshd_config.d.bak.$(date +%Y%m%d-%H%M%S)"
cp -r /etc/ssh/sshd_config.d "$SSH_BACKUP"
log "Backed up SSH configs to $SSH_BACKUP"

# Remove the conflicting duplicate file
if [[ -f /etc/ssh/sshd_config.d/hardening.conf ]]; then
    rm /etc/ssh/sshd_config.d/hardening.conf
    log "Removed duplicate hardening.conf"
fi

# Write consolidated hardened config
cat > /etc/ssh/sshd_config.d/99-hardened.conf << 'SSHEOF'
# Consolidated SSH hardening — generated by harden-homelab.sh
# Authentication
PasswordAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
PermitEmptyPasswords no
PermitRootLogin no
KerberosAuthentication no
GSSAPIAuthentication no

# Access control
AllowUsers dev svc-ai-agent

# Network
ListenAddress 192.168.8.101
ListenAddress 100.114.75.127

# Session limits
LoginGraceTime 30
MaxAuthTries 3
MaxSessions 5
ClientAliveInterval 300
ClientAliveCountMax 2

# Hardened ciphers (with post-quantum KEX)
KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
HostKeyAlgorithms ssh-ed25519,rsa-sha2-512,rsa-sha2-256

# Disable unnecessary features
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no
GatewayPorts no

# Logging
LogLevel VERBOSE

# Banner
Banner /etc/ssh/banner.txt
SSHEOF
log "Wrote consolidated /etc/ssh/sshd_config.d/99-hardened.conf"

# Ensure svc-ai-agent Match block is unchanged (already well-locked)
log "Keeping svc-ai-agent.conf Match block as-is"

# Validate config before restart
if sshd -t 2>&1 | tee -a "$LOG_FILE"; then
    log "SSH config validation passed"
else
    err "SSH config validation FAILED — restoring backup"
    rm -rf /etc/ssh/sshd_config.d
    mv "$SSH_BACKUP" /etc/ssh/sshd_config.d
    err "Backup restored. Fix the config manually and re-run."
    exit 1
fi

# =============================================================================
# STEP 2: SSH Banner
# =============================================================================
log "=== STEP 2: SSH Banner ==="

cat > /etc/ssh/banner.txt << 'BANNEREOF'
***************************************************************************
*                         AUTHORIZED ACCESS ONLY                          *
*                                                                         *
*  This system is privately owned. Unauthorized access is prohibited.     *
*  All connections are monitored and logged. By proceeding, you consent   *
*  to monitoring and agree that evidence of unauthorized activity may be  *
*  used in legal proceedings.                                             *
*                                                                         *
*  Disconnect IMMEDIATELY if you are not an authorized user.              *
***************************************************************************
BANNEREOF
chmod 644 /etc/ssh/banner.txt
log "Created /etc/ssh/banner.txt"

# =============================================================================
# STEP 3: Harden UFW Rules
# =============================================================================
log "=== STEP 3: UFW Firewall ==="

echo ""
warn "Current UFW rules with 'Anywhere' (non-Calico):"
ufw status numbered | grep -i "anywhere" | grep -v "calico\|cali" || true
echo ""

if confirm "Replace Anywhere rules for 80/443 with LAN + Tailscale scoped rules?"; then
    # Delete Anywhere rules for 80 and 443 (in reverse order to avoid index shifts)
    # We need to get rule numbers dynamically
    while ufw status numbered | grep -E "443/tcp.*ALLOW IN.*Anywhere\b" | grep -v "calico\|cali\|v6" | head -1 | grep -q .; do
        RULE_NUM=$(ufw status numbered | grep -E "443/tcp.*ALLOW IN.*Anywhere\b" | grep -v "calico\|cali\|v6" | head -1 | sed 's/\[ *\([0-9]*\)\].*/\1/')
        if [[ -n "$RULE_NUM" ]]; then
            echo "y" | ufw delete "$RULE_NUM" 2>&1 | tee -a "$LOG_FILE"
            log "Deleted Anywhere rule #$RULE_NUM for 443/tcp"
        fi
    done

    while ufw status numbered | grep -E "80/tcp.*ALLOW IN.*Anywhere\b" | grep -v "calico\|cali\|v6" | head -1 | grep -q .; do
        RULE_NUM=$(ufw status numbered | grep -E "80/tcp.*ALLOW IN.*Anywhere\b" | grep -v "calico\|cali\|v6" | head -1 | sed 's/\[ *\([0-9]*\)\].*/\1/')
        if [[ -n "$RULE_NUM" ]]; then
            echo "y" | ufw delete "$RULE_NUM" 2>&1 | tee -a "$LOG_FILE"
            log "Deleted Anywhere rule #$RULE_NUM for 80/tcp"
        fi
    done

    # Delete IPv6 Anywhere rules for 80 and 443
    while ufw status numbered | grep -E "443/tcp \(v6\).*ALLOW IN.*Anywhere \(v6\)" | grep -v "calico\|cali" | head -1 | grep -q .; do
        RULE_NUM=$(ufw status numbered | grep -E "443/tcp \(v6\).*ALLOW IN.*Anywhere \(v6\)" | grep -v "calico\|cali" | head -1 | sed 's/\[ *\([0-9]*\)\].*/\1/')
        if [[ -n "$RULE_NUM" ]]; then
            echo "y" | ufw delete "$RULE_NUM" 2>&1 | tee -a "$LOG_FILE"
            log "Deleted IPv6 Anywhere rule #$RULE_NUM for 443/tcp"
        fi
    done

    while ufw status numbered | grep -E "80/tcp \(v6\).*ALLOW IN.*Anywhere \(v6\)" | grep -v "calico\|cali" | head -1 | grep -q .; do
        RULE_NUM=$(ufw status numbered | grep -E "80/tcp \(v6\).*ALLOW IN.*Anywhere \(v6\)" | grep -v "calico\|cali" | head -1 | sed 's/\[ *\([0-9]*\)\].*/\1/')
        if [[ -n "$RULE_NUM" ]]; then
            echo "y" | ufw delete "$RULE_NUM" 2>&1 | tee -a "$LOG_FILE"
            log "Deleted IPv6 Anywhere rule #$RULE_NUM for 80/tcp"
        fi
    done

    # Add scoped rules
    ufw allow from "$LAN_CIDR" to any port 443 proto tcp comment "HTTPS - LAN" 2>&1 | tee -a "$LOG_FILE" || true
    ufw allow from "$TAILSCALE_CIDR" to any port 443 proto tcp comment "HTTPS - Tailscale" 2>&1 | tee -a "$LOG_FILE" || true
    ufw allow from "$LAN_CIDR" to any port 80 proto tcp comment "HTTP - LAN" 2>&1 | tee -a "$LOG_FILE" || true
    ufw allow from "$TAILSCALE_CIDR" to any port 80 proto tcp comment "HTTP - Tailscale" 2>&1 | tee -a "$LOG_FILE" || true
    log "Added LAN + Tailscale scoped rules for 80/443"
fi

# Add SSH rate limiting for Tailscale (idempotent — ufw skips duplicates)
ufw limit from "$TAILSCALE_CIDR" to any port 22 proto tcp comment "SSH rate limit - Tailscale" 2>&1 | tee -a "$LOG_FILE" || true
log "SSH rate limiting configured for Tailscale"

ufw reload 2>&1 | tee -a "$LOG_FILE"
log "UFW reloaded"

# =============================================================================
# STEP 4: Kernel Hardening (sysctl)
# =============================================================================
log "=== STEP 4: Kernel Hardening (sysctl) ==="

cat > /etc/sysctl.d/99-hardening.conf << 'SYSCTLEOF'
# Security hardening — generated by harden-homelab.sh
# Disable ICMP redirects (prevent MITM)
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0

# Log martian packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2

# ASLR (should already be 2)
kernel.randomize_va_space = 2

# Restrict kernel pointers and dmesg
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1

# Disable core dumps for SUID binaries
fs.suid_dumpable = 0

# Ignore bogus ICMP errors
net.ipv4.icmp_ignore_bogus_error_responses = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1

# NOTE: rp_filter is managed by MicroK8s (10-microk8s.conf) — do NOT override here
# NOTE: ip_forward=1 is required for K8s — do NOT disable here
SYSCTLEOF

# Remove conflicting rp_filter from this file if it existed in the old version
log "Wrote /etc/sysctl.d/99-hardening.conf (rp_filter deferred to MicroK8s)"

sysctl --system 2>&1 | tail -5 | tee -a "$LOG_FILE"
log "sysctl applied"

# =============================================================================
# STEP 5: Enable Audit Logging (auditd)
# =============================================================================
log "=== STEP 5: Audit Logging ==="

if ! dpkg -l | grep -q "^ii.*auditd"; then
    log "Installing auditd..."
    apt-get update -qq && apt-get install -y -qq auditd audispd-plugins 2>&1 | tee -a "$LOG_FILE"
else
    log "auditd already installed"
fi

cat > /etc/audit/rules.d/hardening.rules << 'AUDITEOF'
# Security hardening audit rules — generated by harden-homelab.sh

# Delete all existing rules (start clean on auditd restart)
-D

# Set buffer size
-b 8192

# Monitor SSH key files
-w /etc/ssh/sshd_config -p wa -k sshd_config
-w /etc/ssh/sshd_config.d/ -p wa -k sshd_config
-w /home/ -p wa -k ssh_keys

# Monitor authentication
-w /etc/passwd -p wa -k identity
-w /etc/group -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/gshadow -p wa -k identity

# Monitor sudoers
-w /etc/sudoers -p wa -k sudoers
-w /etc/sudoers.d/ -p wa -k sudoers

# Monitor login/logout
-w /var/log/auth.log -p wa -k auth_log
-w /var/log/faillog -p wa -k login_failures
-w /var/log/lastlog -p wa -k login_tracking

# Monitor time changes
-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time_change
-w /etc/localtime -p wa -k time_change

# Monitor cron
-w /etc/crontab -p wa -k cron
-w /etc/cron.d/ -p wa -k cron
-w /var/spool/cron/ -p wa -k cron

# Monitor kernel modules
-w /sbin/insmod -p x -k kernel_modules
-w /sbin/rmmod -p x -k kernel_modules
-w /sbin/modprobe -p x -k kernel_modules

# Make rules immutable (requires reboot to change)
-e 2
AUDITEOF

systemctl enable auditd 2>&1 | tee -a "$LOG_FILE" || true
systemctl restart auditd 2>&1 | tee -a "$LOG_FILE"
log "auditd enabled and started with hardening rules"

# =============================================================================
# STEP 6: Harden Fail2ban
# =============================================================================
log "=== STEP 6: Fail2ban ==="

cat > /etc/fail2ban/jail.local << 'F2BEOF'
# Fail2ban hardening — generated by harden-homelab.sh
[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 3
banaction = ufw

[sshd]
enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.log
backend  = systemd
maxretry = 3
bantime  = 1h

[recidive]
enabled  = true
filter   = recidive
logpath  = /var/log/fail2ban.log
bantime  = 1w
findtime = 1d
maxretry = 3
F2BEOF

systemctl restart fail2ban 2>&1 | tee -a "$LOG_FILE"
log "Fail2ban configured with sshd + recidive jails"

# =============================================================================
# STEP 7: Identify Unknown Listening Ports
# =============================================================================
log "=== STEP 7: Port Audit ==="

warn "Services listening on 0.0.0.0 (non-localhost):"
ss -tlnp | grep "0.0.0.0" | grep -v "127.0.0" | while read -r line; do
    PORT=$(echo "$line" | awk '{print $4}' | rev | cut -d: -f1 | rev)
    PROC=$(echo "$line" | grep -oP 'users:\(\("\K[^"]+' || echo "unknown")
    echo "  Port $PORT — Process: $PROC" | tee -a "$LOG_FILE"
done
echo ""
warn "Review the ports above. Services on 0.0.0.0 are reachable from all interfaces."
warn "Consider binding Syncthing GUI (8384) and unknown ports (44321-44323, 4330) to 127.0.0.1."

# =============================================================================
# STEP 8: Restart SSH
# =============================================================================
log "=== STEP 8: Apply SSH Changes ==="

echo ""
warn "About to restart SSH. Ensure you have another session open as a backup!"
if confirm "Restart sshd now?"; then
    # Final validation
    if sshd -t 2>&1 | tee -a "$LOG_FILE"; then
        systemctl restart sshd 2>&1 | tee -a "$LOG_FILE"
        log "sshd restarted successfully"
    else
        err "sshd config test FAILED — NOT restarting. Check the config manually."
    fi
else
    warn "SSH restart skipped. Run 'sudo systemctl restart sshd' manually after verifying."
fi

# =============================================================================
# VERIFICATION SUMMARY
# =============================================================================
echo ""
echo "============================================================================="
echo "                        VERIFICATION SUMMARY"
echo "============================================================================="
echo ""

echo "--- SSH Config ---"
sshd -t 2>&1 && echo -e "${GREEN}PASS${NC}: sshd config valid" || echo -e "${RED}FAIL${NC}: sshd config invalid"
grep "ListenAddress" /etc/ssh/sshd_config.d/99-hardened.conf
echo ""

echo "--- UFW (Anywhere rules) ---"
ANYWHERE_COUNT=$(ufw status | grep -c "Anywhere" 2>/dev/null | grep -v "calico\|cali" || echo "0")
echo "Non-Calico Anywhere rules remaining: $ANYWHERE_COUNT"
echo ""

echo "--- Kernel Hardening ---"
echo "send_redirects: $(sysctl -n net.ipv4.conf.all.send_redirects)"
echo "accept_redirects: $(sysctl -n net.ipv4.conf.all.accept_redirects)"
echo "log_martians: $(sysctl -n net.ipv4.conf.all.log_martians)"
echo "tcp_syncookies: $(sysctl -n net.ipv4.tcp_syncookies)"
echo "randomize_va_space: $(sysctl -n kernel.randomize_va_space)"
echo ""

echo "--- Audit Logging ---"
systemctl is-active auditd 2>&1 && echo -e "${GREEN}PASS${NC}: auditd active" || echo -e "${RED}FAIL${NC}: auditd not active"
RULE_COUNT=$(auditctl -l 2>/dev/null | wc -l || echo "0")
echo "Audit rules loaded: $RULE_COUNT"
echo ""

echo "--- Fail2ban ---"
systemctl is-active fail2ban 2>&1 && echo -e "${GREEN}PASS${NC}: fail2ban active" || echo -e "${RED}FAIL${NC}: fail2ban not active"
fail2ban-client status 2>/dev/null | grep "Jail list" || true
echo ""

echo "--- Post-Quantum KEX ---"
grep -q "sntrup761" /etc/ssh/sshd_config.d/99-hardened.conf && echo -e "${GREEN}PASS${NC}: PQ KEX configured" || echo -e "${RED}FAIL${NC}: PQ KEX missing"
echo ""

echo "============================================================================="
log "Hardening complete. Log saved to $LOG_FILE"
echo "============================================================================="
echo ""
echo "NEXT STEPS:"
echo "  1. From another machine, test SSH:  ssh dev@$LAN_IP"
echo "  2. From Tailscale:                  ssh dev@$TAILSCALE_IP"
echo "  3. Review port audit output above and bind services to localhost if needed"
echo "  4. Consider scheduling kernel update reboots (Automatic-Reboot is disabled)"
echo ""
